### ISSUE TITLE
Getting double builds for cross-compile jobs when SIMD optimizations enabled with microarch-level

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/microarch-level-feedstock#11]
### Comment:

As described in https://github.com/conda-forge/pythia8-feedstock/issues/53, I've noticed that for feedstocks with microarch-level enabled _and_ cross-compile builds (`linux-aarch64`, `linux-ppc64le`, and `osx-arm64`) that the cross-compile builds are getting built twice for no clear reason.

> I've noticed that the cross-compile builds (`linux-aarch64`, `linux-ppc64le`, and `osx-arm64`) are getting built twice for reasons I don't understand. This can be seen on https://anaconda.org/conda-forge/pythia8/files if you search for "`linux-aarch64/pythia8-8.312-py312`" then both `linux-aarch64/pythia8-8.312-py312h9243d74_0.conda` and `linux-aarch64/pythia8-8.312-py312hd40b618_0.conda` are found. Similarly, if inspected on https://prefix.dev/channels/conda-forge/packages/pythia8 there seems to be no reported difference in the dependencies.
> 
> ![Image](https://github.com/user-attachments/assets/f67e0f77-3fa0-444f-8331-3fa7937308e4)
> 
> This does not happen with other cross-compiled packages like LHAPDF: https://anaconda.org/conda-forge/lhapdf/files?version=6.5.4

Can anyone advise as to what that might be?

Example feedstocks:
* [conda-forge/pythia8-feedstock](https://github.com/conda-forge/pythia8-feedstock/blob/825e5cae758bf6895668827ab86e594cad130dbe/recipe/meta.yaml)
* [conda-forge/awkward-cpp-feedstock](https://github.com/conda-forge/awkward-cpp-feedstock/blob/7b4a7ff7da7e9521cceee4c585dc6e602f79f4b0/recipe/meta.yaml)
* [conda-forge/blasfeo-feedstock](https://github.com/conda-forge/blasfeo-feedstock/blob/969686656aca06904642b9df839fd0bdb36a82ab/recipe/meta.yaml)

cc @baszalmstra as this might be of general interest to them.

**Comment by matthewfeickert** [comment]
Hm, from looking at the finished build information

```
INFO :: The inputs making up the hashes for the built packages are as follows:
{
  "pythia8-8.312-py313h5d0742a_1.conda": {
    "recipe": {
      "build_platform": "linux-64",
      "c_compiler": "gcc",
      "c_compiler_version": "13",
      "c_stdlib": "sysroot",
      "c_stdlib_version": "2.17",
      "channel_targets": "conda-forge main",
      "cxx_compiler": "gxx",
      "cxx_compiler_version": "13",
      "microarch_level": "3",
      "python": "3.13.* *_cp313",
      "target_platform": "linux-aarch64",
      "zlib": "1"
    }
  },
  "pythia8-8.312-py313hebd5f3a_1.conda": {
    "recipe": {
      "build_platform": "linux-64",
      "c_compiler": "gcc",
      "c_compiler_version": "13",
      "c_stdlib": "sysroot",
      "c_stdlib_version": "2.17",
      "channel_targets": "conda-forge main",
      "cxx_compiler": "gxx",
      "cxx_compiler_version": "13",
      "microarch_level": "1",
      "python": "3.13.* *_cp313",
      "target_platform": "linux-aarch64",
      "zlib": "1"
    }
  }
}
```

The difference is the `microarch_level`, but as far as I know the `microarch_level` is only useful if the `target_platform` is an `x86` platform. @isuruf Is this because [I have](https://github.com/conda-forge/pythia8-feedstock/blob/825e5cae758bf6895668827ab86e594cad130dbe/recipe/meta.yaml#L27-L34)

```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

and not

```yaml
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64 and (build_platform == target_platform)]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
```

?
