### ISSUE TITLE
Why is level 2 not shown in the knowledge base docs?

### ISSUE THREAD

**Issue by matthewfeickert** [conda-forge/microarch-level-feedstock#12]
### Comment:

From the feedstock it seems that microarch level 2 is intended and supported:

https://github.com/conda-forge/microarch-level-feedstock/blob/343bcd72c1897c63ed102dff3b45a483f828f18d/recipe/gen.py#L8-L11

However, it is not shown in the [conda-forge maintainer docs Knowledge Base example](https://conda-forge.org/docs/maintainer/knowledge_base/#microarch):

`recipe/conda_build_config.yaml`
```yaml
microarch_level:
  - 1
  - 3  # [unix and x86_64]
  - 4  # [unix and x86_64]
```

`recipe/meta.yaml`
```yaml
# ...
{% set build = 0 %}

build:
  number: {{ build }}          # [not (unix and x86_64)]
  number: {{ build + 100 }}    # [unix and x86_64 and microarch_level == 1]
  number: {{ build + 300 }}    # [unix and x86_64 and microarch_level == 3]
  number: {{ build + 400 }}    # [unix and x86_64 and microarch_level == 4]

requirements:
  build:
    - x86_64-microarch-level {{ microarch_level }}  # [unix and x86_64]
    - {{ compiler('c') }}
    # ...
# ...
```

Is there a reason for this? Perhaps I am missing something about the x86 microarches that should be obvious.
