### ISSUE TITLE
Example of using ppc64le microarchs?

### ISSUE THREAD

**Issue by lgray** [conda-forge/microarch-level-feedstock#17]
### Comment:

I tried adding variants like:
```yaml
x86_64_microarch_level:
  - if: unix and x86_64
    then:
      - 1
      - 3
      # Level 4 might not be available on the build machine
      # - "4"
ppc64le_microarch_level:
  - if: unix and ppc64le
    then:
      - 8
      - 9
      - 10
```

In my build section I included:
```yaml
      build:
        - if: unix and x86_64
          then: x86_64-microarch-level ==${{ x86_64_microarch_level }}
        - if: unix and ppc64le
          then: ppc64le-microarch-level ==${{ ppc64le_microarch_level }}
```
Nothing in host.

And this always results in failed builds for ppc64le cross compilation when determining host env, here is an example for `8`:
```
 │ │ Resolving host environment:
 │ │   Platform: linux-ppc64le [__unix=0=0, __linux=6.11.0=0, __glibc=2.34=0, __archspec=1=x86_64_v4]
 │ │   Channels: 
 │ │    - file:///home/conda/feedstock_root/build_artifacts/
 │ │    - conda-forge
 │ │   Specs:
 │ │    - _ppc64le-microarch-level >=8
 │ │    - gmp 6.*
 │ │    - mpfr 4.*
 │ │    - siscone
 │ │    - libstdcxx >=13
 │ │    - libgcc >=13
 │ │    - _ppc64le-microarch-level >=8
 │ │
 │ ╰─────────────────── (took 27 seconds)
 │
 ╰─────────────────── (took 27 seconds)
Error:   × Failed to resolve dependencies: Cannot solve the request because of:
  │ _ppc64le-microarch-level >=8 cannot be installed because there are no
  │ viable options:
  │ └─ _ppc64le-microarch-level 8 | 8 | 8 | 8 | 8 | 8 | 9 | 9 | 9 | 10 | 10 |
  │ 10 would require
  │    └─ __archspec ==1 ppc64le, for which no candidates were found.
  │ 
  ╰─▶ Cannot solve the request because of: _ppc64le-microarch-level >=8 cannot
      be installed because there are no viable options:
      └─ _ppc64le-microarch-level 8 | 8 | 8 | 8 | 8 | 8 | 9 | 9 | 9 | 10 | 10
      | 10 would require
         └─ __archspec ==1 ppc64le, for which no candidates were found.
```

I suspect something is going wrong with the `__archspec` virtual package but I really am just guessing.

It would be great (but not absolutely necessary) if I could get x86_64 and ppc64le microarch variants building, mostly I would like to understand what actually works. The documentation is a little thin. I would appreciate any tricks/hints/help. :-)
